[project]
name = "job-recommender-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "langchain-groq>=1.0.0",
    "langchain-mistralai>=1.0.1",
    "langchain-text-splitters>=1.0.0",
    "mcp-use>=1.4.0",
    "pymupdf>=1.26.6",
    "tenacity>=9.1.2",
]
